### PR TITLE
Save warning log

### PR DESCRIPTION
**Pull request by MidwayMarshall**
don't update mafia.js just yet

### CODE REVIEW

**Comment by PokeWorldBW** [comment]
Oh, I was going to expand warnings beyond this and using memory hash instead o.o

**Comment by MidwayMarshall** [comment]
You could use hash I guess. Is there a point to using it for this case?

**Comment by PokeWorldBW** [comment]
Not 100% sure, but I modeled it off the mute/smute/mafiaban/hangmanban/safariban stuff. I think in the past coyo said it was better than having to read and parse files from JSON constantly, which was why I think Trivia was changed to use it.

**Comment by StrudelsPO** [comment]
any changes or should I merge this?

**Comment by PokeWorldBW** [comment]
Uhh I was going to do this plus more anyway so maybe wait for that? Not sure how much of a hassle it would be to make or change different files to save the warn log in.

**Comment by StrudelsPO** [comment]
o ok

**Comment by StrudelsPO** [comment]
#1532

**Pull request closed without merging**
