### PR TITLE
Added a check notification if the hint pokemon is a valid pokemon in the database.

### PR DESCRIPTION
**Pull request by NightfallAlicorn**

### CODE REVIEW

**Comment by PokeWorldBW** [comment]
Can't you just check if the part of the word before the space is a Pokemon? I don't think any Pokemon normally has a space in its name.

**Comment by NightfallAlicorn** [comment]
The script removes hyphens during that phase of the script and replaces them with spaces. The array is to check the missing forms that don't exist in sys.pokeNum(). I hadn't added Unown letters though since I never see people do Unown Z or others. Actually that may be an issue if a user did do that kinda Unown game. :o

**Comment by NightfallAlicorn** [comment]
Never mind about the Unown thing. They not allowed.

**Comment by PokeWorldBW** [comment]
What I'm saying is that all the possible form variations are the Pokemon's name followed by a space and then the form name. You can just make it check if the part of the answer before the space is a valid Pokemon instead of having an array with all the form possibilities, which isn't necessary.

**Comment by NightfallAlicorn** [comment]
If I'm correct. You mean like RegExp check if part of a Pokémon name exists? That can work. The idea of what I done so far is to make it more solid. I mean someone could spell Origin wrong in Giratina. But should work either way. But it just concerns me someone saying, "But the bot didn't alert me that I spelt it wrong," problem.

**Comment by PokeWorldBW** [comment]
Oh, never mind, woops, ignore my previous comment then :D

**Comment by NightfallAlicorn** [comment]
@PokeWorldBW - Sorry.

**Pull request closed without merging**
