### PR TITLE
ORAS PU?

### PR DESCRIPTION
**Pull request by Arburator**
don't know if done correctly, you'd have to double check...

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
why

**Comment by Arburator** [comment]
smogon uses it for pokemon worse than NU, and people on a forum are moaning at PO for not having it

http://prntscr.com/a7fu6f <--

**Comment by Sulcata** [comment]
This would need to be discussed on the forums and get some sort of approval from Draciel or something.

**Comment by Draciel17** [comment]
This has been discussed so many times already, we don't have the necessary playerbase for any official PU tier. If we somehow magically get that in future, I will reconsider. But for now this isn't happening, sorry.

**Pull request closed without merging**
