### PR TITLE
correction to html

### PR DESCRIPTION
**Pull request by forbiddennightmare**

### CODE REVIEW

**Comment by CrystalMoogle** [comment]
Maybe learn html before committing because this is wrong

**Comment by forbiddennightmare** [comment]
i know more than you obvliously

**Comment by CrystalMoogle** [comment]
that's great considering no one fucking uses </br> it's either <br> or <br />

**Comment by forbiddennightmare** [comment]
rude much

**Comment by SteveC688** [comment]
</brasil??>

**Comment by BarryLangley** [comment]
the fuck is this lmfao

**Pull request closed without merging**
