### PR TITLE
/tourrules only works in tours channel request

### PR DESCRIPTION
**Pull request by NightfallAlicorn**

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
No. Other way. It needs to send to the channel you use the command on.

**Comment by NightfallAlicorn** [comment]
Thought the request was the channel itself, it already could send to all channels with me?

**Comment by Fuzzysqurl** [comment]
It prints in tourschan no matter what channel you use the command in. It should print in the channel you use the command in.

**Comment by NightfallAlicorn** [comment]
I see. Okay, I just change it. Sorry about that.

**Comment by NightfallAlicorn** [comment]
Err, I can't edit the pull, could  you unlock please, saves wasting space making another pr? I've got it ready.

**Comment by Fuzzysqurl** [comment]
No cause it would have a commit, then another commit that reverses the first commit cause I know you use web interface :)

**Comment by Fuzzysqurl** [comment]
And only I'm allowed to be messy with commits while trying to fix things.

**Pull request closed without merging**
