### PR TITLE
trying git again updated bot and tidy main script with gastly added for silent

### PR DESCRIPTION
**Pull request by NightfallAlicorn**
**server restart required**
Chances I may add and tidy more stuff.

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
why

**Comment by NightfallAlicorn** [comment]
- other bots can now use other colors like tours bot
- main script easier to read
- silentbot is only staff can see, i thought everyone saw my smute time back
- main script easier to read since the indents were making it hard
- even tidied indents that were incorrect which readme stats should be 4 indents not 4 + 3 or something

I've tested it, doesn't break anything. Plus adding bit of color make PO look interesting anyway, Strudels doesn't mind having Unown pink (he probably joking but it there anyway).

Also. Is it alright to add a fake HTML tag to notice.html, <notice /> or <notice> or something? Me and Strudels have been discussing about being able to block seeing it for our client scripts. :x

**Comment by NightfallAlicorn** [comment]
Almost forgot, did I mention you can /eval the bot colours? Example hangbot.color = "hex color/color name" :) So it changeable without needing to scripts.js update. Also, other main scripts can call it in their init() calls anyway during plugin updates so you don't have to touch main script.

**Comment by NightfallAlicorn** [comment]
RIP my idea.

**Pull request closed without merging**
