### PR TITLE
Allow colons in cban/cmute reasons

### PR DESCRIPTION
**Pull request by PokeWorldBW**
To allow quotes and stuff
Also prevents fails like (11:30:43) ±Chatot: Water banned loser
permanently from this channel! [Reason: 2h]

### CODE REVIEW

**Comment by PokeWorldBW** [comment]
wait I need to fix something

**Comment by Fuzzysqurl** [comment]
>does channel mutes
>forgets server mutes
pwbw pls

**Comment by PokeWorldBW** [comment]
ok the thing I wanted to fix is done
I didn't want to touch server mutes :x

**Comment by Fuzzysqurl** [comment]
Touch them. Touch them like the dirty girl they are :)

**Comment by PokeWorldBW** [comment]
._.
Don't blame me if server mutes break. brb

**Comment by PokeWorldBW** [comment]
ok Fuzzy, server mutes are done

**Pull request merged**
