### PR TITLE
Minor cleanup of usercommands.js

### PR DESCRIPTION
**Pull request by turbedi**
I hope that I didn't do anything wrong .-.

### CODE REVIEW

**Comment by NightfallAlicorn** [comment]
You missed a space on line 657 before {.

I don't mind helping out with cleaning the code, just last time I offered Crystal just said no and closed the poll without reason on scripts.js.

**Comment by CrystalMoogle** [comment]
I don't like commits that pul

**Comment by CrystalMoogle** [comment]
I don't like commits that purely clean up code. Especially when there's a lot of rewriting that needs to be done. I'll do it one day.

**Comment by NightfallAlicorn** [comment]
No worries, Crystal.

**Pull request closed without merging**
