### PR TITLE
Update tiers.xml

### PR DESCRIPTION
**Pull request by ElizeLutus**
We're bringing Monogen back

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
What's with all the line changes? Aren't you just adding a tier?

**Comment by ElizeLutus** [comment]
Yes, so we changed the DisplayOrder so Monogen is just under Monotype ( mono being at 0, gen was 1, so i basically incremented one to each side meta tier )

**Comment by Fuzzysqurl** [comment]
Your indents at the top :(

**Comment by ElizeLutus** [comment]
That was a mistake when I was modifying in codeblocks soz :x

**Pull request merged**
