### PR TITLE
/cbans search, improve invite/invitespec and separate

### PR DESCRIPTION
**Pull request by PokeWorldBW**
Also fix /unmute telling you that you can't mute yourself (when you're trying to unmute yourself)

Invite change:
Before, you had to wait between every invite, even if it was to different people
This will still prevent a user from being invite spammed by the same person

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
Requires server restart. Not merging till next is planned cause it will break a few things.

**Comment by PokeWorldBW** [comment]
Uhh is there a way for me to submit another pull request while this one is still open?

**Comment by turbedi** [comment]
Create a new branch here: http://puu.sh/mHgTH.png
and edit the things you want to edit. After that you can just create a new pull request

**Comment by NightfallAlicorn** [comment]
click here and edit the file you wanna edit on top-right
https://github.com/po-devs/po-server-goodies/pull/1260/files

**Comment by PokeWorldBW** [comment]
Oh, okay, thanks

**Comment by Fuzzysqurl** [comment]
Able to squish? :)

**Comment by PokeWorldBW** [comment]
sure

**Pull request closed without merging**
