### PR TITLE
leaderboard corrects name casing after winning events

### PR DESCRIPTION
**Pull request by NightfallAlicorn**
This was a struggle. I would advise having getProp() as a prototype though.

### CODE REVIEW

**Comment by StrudelsPO** [comment]
don't we have something like .toCorrectCase() or am i being dum

**Comment by NightfallAlicorn** [comment]
That function is to get the correct case out the object, not getting their sys.name current name if I recall. :x

**Comment by StrudelsPO** [comment]
oh i overlooked the loop through the object

well this works too ･◡･

**Comment by Fuzzysqurl** [comment]
ToCorrectCase literally returns sys.name

"fuzzysqurl".tocorrectcase = Fuzzysqurl
"SULCATA".tocorrectcase = sulcata
"Nightmare moon".tocorrectcase = Nightmare Moon

**Comment by StrudelsPO** [comment]
i was actually under the impression that if you just added "Nightmare Moon" points +1 to the lb which already stores a "nightmare moon" it'd give the former a new record instead of updating the uncased one, so we'd need getPropCase to loop through and then you delete the old uncased record and re-add it with their proper name. 

If it does update on its own then yeah you could literally just write w points +1 to the file and be done. Also it only dawned on me from just now that w is already in correct case so you wouldn't even have to w.toCorrectCase(), which has the benefit of updating offline winners as well.

**Pull request merged**
