### PR TITLE
Pyramid HazardRoom

### PR DESCRIPTION
**Pull request by moonstruckminun**
This is a change I suggested in the thread some months ago, then eventually tested on another server in a heavily modified version of pyramid while PO's pyramid was down. 

The changes are:
- Exactly 3 Hazards per Hazard Room
- Hazard Rooms tells you what the 3 Hazards are 
- Added Spider Web (Rapid Spin or Struggle Bug to remove) - adds difficulty because otherwise this update makes Hazard Rooms way easier, and also makes some more unique mons more viable like Flygon or Delibird.

Pros:
- Requires a lot more fast communication between team members. Like all 3 of you have to commit to clearing a different hazard, or all of you are doomed.
- Also rewards knowing not only what your own party can do, but having an idea of what the mons in your teammates' parties are capable of clearing.
- No more annoying "You cleared 6% of the Stream" and "you all died to 90% of invisible Electric Fence that wasn't there"
- It was lots of fun when testing

Cons:
I suppose you're really screwed when you're the last player alive on your team, but that's true for most any room. 

This is tested, but not with the newer version of pyramid, so if there are any changed functions that it calls they will need to be updated. (I scanned through to see if there were but it's hard to catch these things.)

### CODE REVIEW

**Comment by IceKirby** [comment]
This would hardly really become a "Communication Skill-based" room unless it removed the broadcast message or locked the choices once made. I dislike this idea since it would just become a "Read and Click" room with hardly any actual challenge (Horde rooms were like this, which is why in the old version people considered it the easier room of all).

**Comment by moonstruckminun** [comment]
You might be surprised how much communication it takes. Since you don't necessarily know which hazards your teammates can clear, you can get situations where everyone's HM choices overlap. Like this:

Hazards: Stream, Fence, Ice Pillar
P1 has Surf, Disable, Heat Wave
P2 has Surf, Disable
P3 has Disable and Heat Wave.

At first, P1 and P2 do Surf, and P3 does Heat Wave. Then they realize no one is taking out the fence and switch to Disable more or less at the same time. Without communication, this is a train wreck. With communication, however, they can sort it out and make sure only 1 person (P1 or P2) switches to Disable. 

But this is a lot of information to sort out in just ~a dozen seconds. Between reading what the three hazards are, taking note which moves you have and finding the ones that are useful for that room, seeing what your teammates are doing, and committing to one hazard while all your teammates do the same, it's hardly "read and click" - at the very worst, you can try playing it as a "read, think a lot, and click" room, but your party will die fast if no one communicates. On the contrary, I found this room to be the most mentally exhausting one when testing it, simply because there was so much information to take in and put to use, and meanwhile your teammates are yelling things like "one of you has to switch i don't have X!".

Here's a more difficult example.
Boulder/Pit/Flamethrower
P1: Superpower
P2: Fly, Superpower
P3: Fly, Hydro Pump.

From the omniscient perspective, it's clear that P2 should Fly and P3 should Hydro Pump. But if you were P2, what would you do if you saw P1 used Superpower and P3 used Fly? You have to communicate. And it's really hard to make a decision given the limited information you have and only a dozen seconds. (It's not as simple as 'do Fly, because then P3 will know to change' because you don't know whether P1 or P3 has Hydro Pump or if either do at all.)

Re: locking choices/remove broadcast, if you think it needs to be harder and limit information more, sure? But I really recommend you test it as is to see if it needs to be more difficult. There will be some rounds where everyone can clear the hazards fine, but if you let your guard down and read-click without communicating, you can screw your whole team.

**Comment by moonstruckminun** [comment]
My question I guess is how is the current Hazard Room not a "read and click" without any actual challenge? It would be the easiest room if not for being mostly luck. The degree to which it requires actual interaction you can do with no problem as long as you know which moves do what. The only question is whether it's a good idea to struggle or aim for a known hazard, and mathematically, the former is useless unless you're trying to prevent the leader from dying.

**Comment by IceKirby** [comment]
Trying to guess which hazards may or may not be around is more challenging than not having to guess anything at all. Everything that players may need to do in a open setup they will also need to in a closed one. 

The reason I'm skeptical about this kind of change increasing the challenge is because it's way easier to communicate by clicking the links than by actually saying "I can't deal with X". I've seen several times that, when there are 2 hazards revealed and all 3 players go for the same one, one of them will change their move without anyone saying any word, just by paying attention to the broadcast messages.

**Comment by moonstruckminun** [comment]
Re: "Everything that players may need to do in a open setup they will also need to in a closed one" - In the closed setup, there's no need for everyone to assign themselves to a specific hazard. Everyone basically does their own thing. And, if there are 2 hazards revealed, it's easy to map 3 players to 2 hazards. 3 players to 3 hazards is harder. Furthermore, knowing there's 3 hazards requires you to keep track of so much information. It can be overwhelming:

3 hazards, 6 moves which can clear them, 2 moves your teammates have input most recently, and what those moves clear. 

This demands way more thinking. Even mapping the moves to their respective hazards takes a lot of memory when there's 3 of them. For a start, figuring out which of the 3 hazards you can personally clear requires a lot of calculations (thus rewarding practice/planning). Then you have to eliminate which of those moves are redundant with what your team is doing - if there's Flamethrowers, and someone's already using Vacuum Wave, you have to remember that Hydro Pump isn't helpful, etc. Because there's so much complicated information, it can actually be useful to communicate direct, simple statements like "cant do boulder" or "dibs on pit".

I feel like this "open" version offers a more complete approach to what hazards rooms can be. In the current version you just have to read the hazards, press a link, and maybe press another link if everyone's on the same hazard. Next to puzzle and statue rooms, which take tons of collaboration and/or time sensitive thinking, hazard rooms don't require anything but luck. If this open version won't work, I hope you'll come up with a patch that makes sense to you.

**Comment by IceKirby** [comment]
I'm open to ideas to improve the rooms, but I want to avoid those that turn the room too mechanized or predictable. What I always wanted for this room was to have a way to give more hints about the existing hazards than to just plain revealing them.
And not only for this room, I wanted ways to give hints that actually put players to think before they act for the StrongMon and Trainer rooms too, but without being too obvious.

I'm closing this since it probably will not be used in this format, but feel free to suggest improvements in the suggestion thread.

**Pull request closed without merging**
