### PR TITLE
Add version check

### PR DESCRIPTION
**Pull request by MidwayMarshall**
Force users to use certain version
or just deny null ids from connecting idk

### CODE REVIEW

**Comment by lamperi** [comment]
Isn't this a little harsh? Maybe remove the kick and keep the message?

**Comment by MidwayMarshall** [comment]
Well with ID bans the easiest way to evade is just to use older versions. Changing proxies doesn't stop it.

**Comment by CrystalMoogle** [comment]
I've always been against forcing an update and will continue to do so. Yes it causes issues, but I'd rather have 1 or 2 problem users than annoying many others.

**Comment by Fuzzysqurl** [comment]
What about just preventing them from talking? idk

**Pull request closed without merging**
